spring:
  jpa:
    database: MYSQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mariadb
    url: jdbc:mariadb://127.0.0.1:3306/deposit_service_database
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

rabbitmq:
  port: 5672
  host: localhost
  username: guest
  password: guest
  listener:
    direct:
      default-requeue-rejected: true

